# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-06 10:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
    ]
